<div class="header_bar">
	<div class="page_title"><h3 class="left">{#I-15#}</h3></div>
</div><br/>
<div id="input_form">
<form action="{#url#}" method="post" class="user_add">
<input type="hidden" name="step" value="cfg" />

{#message#}

<!-- begin buttons -->
<div class="submit_btn">
	<p class="submit"><input class="left try_me" type="submit" value="{#button#}" /></p>
</div>
<!-- end buttons -->
</form>
</div>