<div class="header_bar">
	<div class="page_title"><h3 class="left">{#I-12#}</h3></div>
</div><br/>

<p class="error">{#ERROR#}</p>

<p>{#I-13#}</p>

<form action="{#url#}" method="post" class="user_add">
<input type="hidden" name="step" value="db" />
<div class="submit_btn">
	<p class="submit"><input class="left try_me" type="submit" value="Back" /></p>
</div>
<!-- end buttons -->
</form>