<div class="header_bar">
	<div class="page_title"><h3 class="left">{#I-01#}</h3></div>
</div><br/>

<div id="input_form">
<form action="{#url#}" method="post" class="user_add">
<input type="hidden" name="step" value="admin" />
<div class="input"><p>{#I-02#}</p><select name='lang' id="lang"><option value='0'>{#I-23#}</option>{#options#}</select></div>

<!-- begin buttons -->
<div class="submit_btn">
	<p class="submit"><input class="left try_me" type="submit" value="{#I-03#}" /></p>
</div>
<!-- end buttons -->
</form>
</div>
<script type="text/javascript">
	document.getElementById('lang').value = "{#lang#}";
</script>