<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="{#direction#}" lang="en-US">

<!-- BEGIN html head -->
<meta http-equiv="Content-Type" content="text/html; charset={#charset#}" />
<title>{#G-01#}</title>
<link rel="stylesheet" type="text/css" href="installer/data/templates/style.css" />

<!--RTL-->
</head>
<!-- END html head -->

<body>

<!-- BEGIN wrapper -->
<div id="main">

	<div id="headerBar">
	    <div class="left">
		<div class="pad_top_5 margin_left_25">
		    <a href="http://www.owasp.org" target="_blank">
		    <!-- style used inline because it will not be repeated elsewhere in the webapp -->
			<img id="orglogo" src="../assets/images/owasp.png">
		    </a>
		</div>
	    </div>
	    <div class="center pad_25">
		<img id="logo" src="../assets/images/logo.png">
	    </div>     
	</div><br/><br/>
	
<div id="wrapper"><div class="buffer">
	<!-- BEGIN body -->
	<div id="body">
	<table>
		<tr>
			<td style="width:70%">
				<div id="content">
				{#DATA#}
				</div>
			</td>
			<td style="width:30%" valign="top">
				<!-- BEGIN sidebar -->
				<div id="sidebar">
				
					<!-- begin SAMPLE sidebar menu -->
					<h2>{#G-02#}</h2><hr/>
					<ul>
					<li {#LINK1#}>{#G-03#}</li>
					<li {#LINK2#}>{#G-07#}</li>
					<li {#LINK3#}>{#G-04#}</li>
					<li {#LINK4#}>{#G-05#}</li>
					<li {#LINK5#}>{#G-06#}</li>
					
					</ul>
					<!-- end SAMPLE sidebar menu -->
				
				</div>
				<!-- END sidebar -->
			</td>
		</tr>
	</table>
	<!-- BEGIN content -->
	
	<!-- END content -->
	
	
	
	<div class="break"></div>
	</div>
	<!-- END body -->

</div></div>
<!-- END wrapper -->

</div>
</body>

</html>
